server:
  port: 8888
  servlet:
    context-path: /sdata/v1/rest

spring:

  # 数据库连接配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/hillbo
    username: root
    password: 123456

    # druid配置
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 配置初始化大小、最小、最大
      initial-size: 1
      min-idle: 3
      max-active: 20
      # 配置获取连接等待超时的时间,单位是毫秒
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: "SELECT 'x' FROM DUAL"
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false


mybatis:
  mapperLocations: classpath*:com/ibigsea/bootdao/mapper/*.xml
  typeAliasesPackage: com.ibigsea.bootdao.entity

